### ISSUE TITLE
MC Controls Suck

### ISSUE THREAD

**Issue by xAmaranth** [irisong980912/polaris#5]
Currently the MC moves around in absolute terms, relative to the axes of the game space.

This is very counter intuitive, as the camera does not pan with the player, but rotates in one place.

Instead, we should have the player's movement be uniform relative to the perspective of the camera. Other suggestions would be good.

**Comment by xAmaranth** [comment]
What if the player simply moved from predetermined points to other predetermined points? This would allow us to finely control what the player is able to do, and allow us to use spiffier animations. On the down side, this would take away agency from the player, which might detract from the exploration aspect of the game.

**Comment by irisong980912** [comment]
we could have a predetermined space that limits the character movements. Players can easily get lost in the space if not enough limitation and guidance is provided
