### ISSUE TITLE
Constellation Reveal Upon Level Clear

### ISSUE THREAD

**Issue by xAmaranth** [irisong980912/polaris#68]
Beams of light should connect stars to reveal the constellation when the level is cleared.

**Comment by MaddieFish** [comment]
I think it would look nice if the beams of light showed even during gameplay. The animation of the beam itself has a custom shader that is pretty and the player can track what stars they have connected

**Comment by xAmaranth** [comment]
Is this issue resolved?

If so, please remove all labels, and then tag it with "complete", then close the issue.

**Comment by irisong980912** [comment]
Yes
