### ISSUE TITLE
Icons for Off-Screen Stars

### ISSUE THREAD

**Issue by xAmaranth** [irisong980912/polaris#96]
When the camera moves to an isometric position (see #93), the player needs some way of quickly identifying which way they need to go.

Some icons that are placed at the edge of the screen to denote an activated or deactivated star would help a player orient themselves in space ( _lul_ ).

Dependency: #93 must be closed before this can be implemented.

**Comment by MaddieFish** [comment]
Steve's icons: https://drive.google.com/open?id=1h7-tTsMqyzoYQ5hs7z1K2hshNxhD7dqV
